version: '3'

tasks:      
  build:
    cmds: 
      - go mod download
      - task: migrate-storage
      - go build -o auth-server ./cmd/auth-server/main.go
  
  migrate-storage:
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/storage.db --migrations-path=./migrations
  
    